package com.dao.videomonitor;

import java.util.List;
import java.util.Map;

import com.entity.videomonitor.TVmDecoder;

public interface TVmDecoderMapper {
    
    int deleteDecoderByPrimaryKey(String decoderid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    int insertDecoder(TVmDecoder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    int insertDecoderSelective(TVmDecoder record);
    
    int updateDecoderByPrimaryKeySelective(TVmDecoder record);

    int testDecoderExistById(String decoderid);

    int updateDecoderByPrimaryKey(TVmDecoder record);
    
    List<TVmDecoder> selectDecoderByPage(Map<String,Object> cond);
    
    int selectDecoderByPageRowCount(Map<String,Object> cond);
    
    TVmDecoder selectDecoderByPrimaryKey(String decoderid);
}