package com.dao.videomonitor;

import java.util.List;

import com.entity.videomonitor.TVmManufacturer;
import com.entity.videomonitor.TVmManufacturerExample;

public interface TVmManufacturerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int countByExample(TVmManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int deleteByExample(TVmManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int deleteByPrimaryKey(String vendorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int insert(TVmManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int insertSelective(TVmManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    List<TVmManufacturer> selectByExample(TVmManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    TVmManufacturer selectByPrimaryKey(String vendorid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int updateByExampleSelective(TVmManufacturer record, TVmManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int updateByExample(TVmManufacturer record, TVmManufacturerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int updateByPrimaryKeySelective(TVmManufacturer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    int updateByPrimaryKey(TVmManufacturer record);
    
    List<TVmManufacturer> selectAll();
}