package com.dao.videomonitor;

import java.util.List;
import java.util.Map;

import com.entity.videomonitor.TVmNvr;
import com.entity.videomonitor.TVmNvrExample;

public interface TVmNvrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int countByExample(TVmNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int deleteByExample(TVmNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int deleteByPrimaryKey(String nvrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int insert(TVmNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int insertSelective(TVmNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    List<TVmNvr> selectByExample(TVmNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    TVmNvr selectByPrimaryKey(String nvrid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int updateByExampleSelective(TVmNvr record, TVmNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int updateByExample(TVmNvr record, TVmNvrExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int updateByPrimaryKeySelective(TVmNvr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_NVR
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    int updateByPrimaryKey(TVmNvr record);
    
    List<TVmNvr> selectByPage(Map<String,Object> cond);
    
    int selectByPageRowCount(Map<String,Object> cond);
    
    List<TVmNvr> selectNvrByRole(Map<String,Object> cond);
    
    int testNvrExistById(String nvrid);
}