package com.service.sounddev.thirdsection;
import com.sun.jna.NativeLong;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public  class TagTalkInfo extends Structure {
	/** 主叫终端ID */
	public NativeLong master_tid;
	/** 被叫终端ID */
	public NativeLong slave_tid;
	/** 主叫终端呼叫状态 */
	public NativeLong master_status;
	/** 主叫终端呼叫状态 */
	public NativeLong slave_status;
	public TagTalkInfo() {
		super();
	}
	protected List<? > getFieldOrder() {
		return Arrays.asList("master_tid", "slave_tid", "master_status", "slave_status");
	}
	/**
	 * @param master_tid 主叫终端ID<br>
	 * @param slave_tid 被叫终端ID<br>
	 * @param master_status 主叫终端呼叫状态<br>
	 * @param slave_status 主叫终端呼叫状态
	 */
	public TagTalkInfo(NativeLong master_tid, NativeLong slave_tid, NativeLong master_status, NativeLong slave_status) {
		super();
		this.master_tid = master_tid;
		this.slave_tid = slave_tid;
		this.master_status = master_status;
		this.slave_status = slave_status;
	}
	public TagTalkInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends TagTalkInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends TagTalkInfo implements Structure.ByValue {
		
	};
}
