package com.entity.videomonitor;

import java.math.BigDecimal;

import net.sf.oval.constraint.Length;
import net.sf.oval.constraint.MatchPattern;
import net.sf.oval.constraint.NotEmpty;
import net.sf.oval.constraint.NotNull;

public class TVmDecoder {
   
	@NotNull(message = "解码器ID不能为空")
	@NotEmpty(message = "解码器ID不能为空")
	@Length(max = 7,message="解码器ID最长为7位")
    private String decoderid;
	@NotNull(message = "IP不能为空")
	@NotEmpty(message = "IP不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "IP格式错误")
    private String ip;
	@NotNull(message = "Port不能为空")
	@NotEmpty(message = "Port不能为空")
	@MatchPattern(pattern = "^\\d+$",message ="Port只能为整数")
    private BigDecimal port;
	@NotNull(message = "用户名不能为空")
	@NotEmpty(message = "用户名不能为空")
    private String username;
	@NotNull(message = "密码不能为空")
	@NotEmpty(message = "密码不能为空")
    private String password;
	@NotNull(message = "设备名称不能为空")
	@NotEmpty(message = "设备名称不能为空")
	@Length(max = 32,message="设备名称最长为32位")
    private String devname;

    private String managementagency;

    private String branch;
    
    private String devictype;
    
    private BigDecimal ordernumber;


	public BigDecimal getOrdernumber() {
		return ordernumber;
	}

	public void setOrdernumber(BigDecimal ordernumber) {
		this.ordernumber = ordernumber;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.IPCID
     *
     * @return the value of T_VM_DECODER.IPCID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getDecoderid() {
        return decoderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.IPCID
     *
     * @param decoderid the value for T_VM_DECODER.IPCID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setDecoderid(String decoderid) {
        this.decoderid = decoderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.IP
     *
     * @return the value of T_VM_DECODER.IP
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.IP
     *
     * @param ip the value for T_VM_DECODER.IP
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.PORT
     *
     * @return the value of T_VM_DECODER.PORT
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public BigDecimal getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.PORT
     *
     * @param port the value for T_VM_DECODER.PORT
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setPort(BigDecimal port) {
        this.port = port;
    }

    
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.USERNAME
     *
     * @param username the value for T_VM_DECODER.USERNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.PASSWORD
     *
     * @return the value of T_VM_DECODER.PASSWORD
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.PASSWORD
     *
     * @param password the value for T_VM_DECODER.PASSWORD
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.DEVNAME
     *
     * @return the value of T_VM_DECODER.DEVNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.DEVNAME
     *
     * @param devname the value for T_VM_DECODER.DEVNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setDevname(String devname) {
        this.devname = devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.DEVFRIENDLYNAME
     *
     * @return the value of T_VM_DECODER.DEVFRIENDLYNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getDevictype() {
        return devictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.DEVFRIENDLYNAME
     *
     * @param devfriendlyname the value for T_VM_DECODER.DEVFRIENDLYNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setDevictype(String devictype) {
        this.devictype = devictype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_DECODER.MANAGEMENTAGENCY
     *
     * @return the value of T_VM_DECODER.MANAGEMENTAGENCY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getManagementagency() {
        return managementagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.MANAGEMENTAGENCY
     *
     * @param managementagency the value for T_VM_DECODER.MANAGEMENTAGENCY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setManagementagency(String managementagency) {
        this.managementagency = managementagency;
    }

    
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_DECODER.IPCPICID
     *
     * @param ipcpicid the value for T_VM_DECODER.IPCPICID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }
}