package com.entity.videomonitor;

import java.math.BigDecimal;

import net.sf.oval.constraint.Length;
import net.sf.oval.constraint.MatchPattern;
import net.sf.oval.constraint.NotEmpty;
import net.sf.oval.constraint.NotNull;

public class TVmIpc {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.IPCID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
	@NotNull(message = "摄像头ID不能为空")
	@NotEmpty(message = "摄像头ID不能为空")
	@Length(max = 7,message="摄像头ID最长为7位")
    private String ipcid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.USERID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
   // private BigDecimal userid;
    private String userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.VENDORID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private TVmManufacturer vendor;
    
//    private BigDecimal vendorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.NVRID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private TVmNvr nvr;
    
//    private BigDecimal nvrid;

//    public BigDecimal getVendorid() {
//		return vendorid;
//	}
//
//	public void setVendorid(BigDecimal vendorid) {
//		this.vendorid = vendorid;
//	}
//
//	public BigDecimal getNvrid() {
//		return nvrid;
//	}
//
//	public void setNvrid(BigDecimal nvrid) {
//		this.nvrid = nvrid;
//	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.IP
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    @NotNull(message = "IP不能为空")
	@NotEmpty(message = "IP不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "IP格式错误")
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.PORT
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    @NotNull(message = "Port不能为空")
	@NotEmpty(message = "Port不能为空")
	@MatchPattern(pattern = "^\\d+$",message ="Port只能为整数")
    private BigDecimal port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.NETMASK
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    @NotNull(message = "netmask不能为空")
	@NotEmpty(message = "netmask不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "netmask格式错误")
    private String netmask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.GATEWAY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    @NotNull(message = "gateway不能为空")
	@NotEmpty(message = "gateway不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "gateway格式错误")
    private String gateway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.USERNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
	@NotNull(message = "用户名不能为空")
	@NotEmpty(message = "用户名不能为空")
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.PASSWORD
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
	@NotNull(message = "密码不能为空")
	@NotEmpty(message = "密码不能为空")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.DEVNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
	@NotNull(message = "devname不能为空")
	@NotEmpty(message = "devname不能为空")
	@Length(max = 32,message="devname最长为32位")
    private String devname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.DEVFRIENDLYNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String devfriendlyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.MANAGEMENTAGENCY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String managementagency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.IPCLONGITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String ipclongitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.IPCLATITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String ipclatitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.VERSION
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_IPC.IPCPICID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    private String branch;
    
    private String devtype;
    
    private int ipcFault;
    
    
    public int getIpcFault() {
		return ipcFault;
	}

	public void setIpcFault(int ipcFault) {
		this.ipcFault = ipcFault;
	}

    public String getDevtype() {
		return devtype;
	}

	public void setDevtype(String devtype) {
		this.devtype = devtype;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.IPCID
     *
     * @return the value of T_VM_IPC.IPCID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getIpcid() {
        return ipcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.IPCID
     *
     * @param ipcid the value for T_VM_IPC.IPCID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setIpcid(String ipcid) {
        this.ipcid = ipcid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.USERID
     *
     * @return the value of T_VM_IPC.USERID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.USERID
     *
     * @param userid the value for T_VM_IPC.USERID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.VENDORID
     *
     * @return the value of T_VM_IPC.VENDORID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public TVmManufacturer getVendor() {
        return vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.VENDORID
     *
     * @param vendorid the value for T_VM_IPC.VENDORID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setVendor(TVmManufacturer vendor) {
        this.vendor = vendor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.NVRID
     *
     * @return the value of T_VM_IPC.NVRID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public TVmNvr getNvr() {
        return nvr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.NVRID
     *
     * @param nvrid the value for T_VM_IPC.NVRID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setNvr(TVmNvr nvr) {
        this.nvr = nvr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.IP
     *
     * @return the value of T_VM_IPC.IP
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.IP
     *
     * @param ip the value for T_VM_IPC.IP
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.PORT
     *
     * @return the value of T_VM_IPC.PORT
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public BigDecimal getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.PORT
     *
     * @param port the value for T_VM_IPC.PORT
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setPort(BigDecimal port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.NETMASK
     *
     * @return the value of T_VM_IPC.NETMASK
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getNetmask() {
        return netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.NETMASK
     *
     * @param netmask the value for T_VM_IPC.NETMASK
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setNetmask(String netmask) {
        this.netmask = netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.GATEWAY
     *
     * @return the value of T_VM_IPC.GATEWAY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.GATEWAY
     *
     * @param gateway the value for T_VM_IPC.GATEWAY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.USERNAME
     *
     * @return the value of T_VM_IPC.USERNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.USERNAME
     *
     * @param username the value for T_VM_IPC.USERNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.PASSWORD
     *
     * @return the value of T_VM_IPC.PASSWORD
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.PASSWORD
     *
     * @param password the value for T_VM_IPC.PASSWORD
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.DEVNAME
     *
     * @return the value of T_VM_IPC.DEVNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.DEVNAME
     *
     * @param devname the value for T_VM_IPC.DEVNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setDevname(String devname) {
        this.devname = devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.DEVFRIENDLYNAME
     *
     * @return the value of T_VM_IPC.DEVFRIENDLYNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getDevfriendlyname() {
        return devfriendlyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.DEVFRIENDLYNAME
     *
     * @param devfriendlyname the value for T_VM_IPC.DEVFRIENDLYNAME
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setDevfriendlyname(String devfriendlyname) {
        this.devfriendlyname = devfriendlyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.MANAGEMENTAGENCY
     *
     * @return the value of T_VM_IPC.MANAGEMENTAGENCY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getManagementagency() {
        return managementagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.MANAGEMENTAGENCY
     *
     * @param managementagency the value for T_VM_IPC.MANAGEMENTAGENCY
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setManagementagency(String managementagency) {
        this.managementagency = managementagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.IPCLONGITUDE
     *
     * @return the value of T_VM_IPC.IPCLONGITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getIpclongitude() {
        return ipclongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.IPCLONGITUDE
     *
     * @param ipclongitude the value for T_VM_IPC.IPCLONGITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setIpclongitude(String ipclongitude) {
        this.ipclongitude = ipclongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.IPCLATITUDE
     *
     * @return the value of T_VM_IPC.IPCLATITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getIpclatitude() {
        return ipclatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.IPCLATITUDE
     *
     * @param ipclatitude the value for T_VM_IPC.IPCLATITUDE
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setIpclatitude(String ipclatitude) {
        this.ipclatitude = ipclatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.VERSION
     *
     * @return the value of T_VM_IPC.VERSION
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.VERSION
     *
     * @param version the value for T_VM_IPC.VERSION
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_IPC.IPCPICID
     *
     * @return the value of T_VM_IPC.IPCPICID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_IPC.IPCPICID
     *
     * @param ipcpicid the value for T_VM_IPC.IPCPICID
     *
     * @mbggenerated Wed Apr 01 00:04:00 CST 2015
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }
}