package com.entity.videomonitor;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TVmIpcExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public TVmIpcExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIpcidIsNull() {
            addCriterion("IPCID is null");
            return (Criteria) this;
        }

        public Criteria andIpcidIsNotNull() {
            addCriterion("IPCID is not null");
            return (Criteria) this;
        }

        public Criteria andIpcidEqualTo(String value) {
            addCriterion("IPCID =", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidNotEqualTo(String value) {
            addCriterion("IPCID <>", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidGreaterThan(String value) {
            addCriterion("IPCID >", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidGreaterThanOrEqualTo(String value) {
            addCriterion("IPCID >=", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidLessThan(String value) {
            addCriterion("IPCID <", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidLessThanOrEqualTo(String value) {
            addCriterion("IPCID <=", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidLike(String value) {
            addCriterion("IPCID like", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidNotLike(String value) {
            addCriterion("IPCID not like", value, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidIn(List<String> values) {
            addCriterion("IPCID in", values, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidNotIn(List<String> values) {
            addCriterion("IPCID not in", values, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidBetween(String value1, String value2) {
            addCriterion("IPCID between", value1, value2, "ipcid");
            return (Criteria) this;
        }

        public Criteria andIpcidNotBetween(String value1, String value2) {
            addCriterion("IPCID not between", value1, value2, "ipcid");
            return (Criteria) this;
        }

        public Criteria andUseridIsNull() {
            addCriterion("USERID is null");
            return (Criteria) this;
        }

        public Criteria andUseridIsNotNull() {
            addCriterion("USERID is not null");
            return (Criteria) this;
        }

        public Criteria andUseridEqualTo(BigDecimal value) {
            addCriterion("USERID =", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotEqualTo(BigDecimal value) {
            addCriterion("USERID <>", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThan(BigDecimal value) {
            addCriterion("USERID >", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("USERID >=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThan(BigDecimal value) {
            addCriterion("USERID <", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridLessThanOrEqualTo(BigDecimal value) {
            addCriterion("USERID <=", value, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridIn(List<BigDecimal> values) {
            addCriterion("USERID in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotIn(List<BigDecimal> values) {
            addCriterion("USERID not in", values, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERID between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andUseridNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("USERID not between", value1, value2, "userid");
            return (Criteria) this;
        }

        public Criteria andVendoridIsNull() {
            addCriterion("VENDORID is null");
            return (Criteria) this;
        }

        public Criteria andVendoridIsNotNull() {
            addCriterion("VENDORID is not null");
            return (Criteria) this;
        }

        public Criteria andVendoridEqualTo(String value) {
            addCriterion("VENDORID =", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotEqualTo(String value) {
            addCriterion("VENDORID <>", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThan(String value) {
            addCriterion("VENDORID >", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThanOrEqualTo(String value) {
            addCriterion("VENDORID >=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThan(String value) {
            addCriterion("VENDORID <", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThanOrEqualTo(String value) {
            addCriterion("VENDORID <=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLike(String value) {
            addCriterion("VENDORID like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotLike(String value) {
            addCriterion("VENDORID not like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridIn(List<String> values) {
            addCriterion("VENDORID in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotIn(List<String> values) {
            addCriterion("VENDORID not in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridBetween(String value1, String value2) {
            addCriterion("VENDORID between", value1, value2, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotBetween(String value1, String value2) {
            addCriterion("VENDORID not between", value1, value2, "vendorid");
            return (Criteria) this;
        }

        public Criteria andNvridIsNull() {
            addCriterion("NVRID is null");
            return (Criteria) this;
        }

        public Criteria andNvridIsNotNull() {
            addCriterion("NVRID is not null");
            return (Criteria) this;
        }

        public Criteria andNvridEqualTo(String value) {
            addCriterion("NVRID =", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridNotEqualTo(String value) {
            addCriterion("NVRID <>", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridGreaterThan(String value) {
            addCriterion("NVRID >", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridGreaterThanOrEqualTo(String value) {
            addCriterion("NVRID >=", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridLessThan(String value) {
            addCriterion("NVRID <", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridLessThanOrEqualTo(String value) {
            addCriterion("NVRID <=", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridLike(String value) {
            addCriterion("NVRID like", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridNotLike(String value) {
            addCriterion("NVRID not like", value, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridIn(List<String> values) {
            addCriterion("NVRID in", values, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridNotIn(List<String> values) {
            addCriterion("NVRID not in", values, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridBetween(String value1, String value2) {
            addCriterion("NVRID between", value1, value2, "nvrid");
            return (Criteria) this;
        }

        public Criteria andNvridNotBetween(String value1, String value2) {
            addCriterion("NVRID not between", value1, value2, "nvrid");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("PORT is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("PORT is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(BigDecimal value) {
            addCriterion("PORT =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(BigDecimal value) {
            addCriterion("PORT <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(BigDecimal value) {
            addCriterion("PORT >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PORT >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(BigDecimal value) {
            addCriterion("PORT <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PORT <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<BigDecimal> values) {
            addCriterion("PORT in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<BigDecimal> values) {
            addCriterion("PORT not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PORT between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PORT not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andNetmaskIsNull() {
            addCriterion("NETMASK is null");
            return (Criteria) this;
        }

        public Criteria andNetmaskIsNotNull() {
            addCriterion("NETMASK is not null");
            return (Criteria) this;
        }

        public Criteria andNetmaskEqualTo(String value) {
            addCriterion("NETMASK =", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskNotEqualTo(String value) {
            addCriterion("NETMASK <>", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskGreaterThan(String value) {
            addCriterion("NETMASK >", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskGreaterThanOrEqualTo(String value) {
            addCriterion("NETMASK >=", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskLessThan(String value) {
            addCriterion("NETMASK <", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskLessThanOrEqualTo(String value) {
            addCriterion("NETMASK <=", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskLike(String value) {
            addCriterion("NETMASK like", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskNotLike(String value) {
            addCriterion("NETMASK not like", value, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskIn(List<String> values) {
            addCriterion("NETMASK in", values, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskNotIn(List<String> values) {
            addCriterion("NETMASK not in", values, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskBetween(String value1, String value2) {
            addCriterion("NETMASK between", value1, value2, "netmask");
            return (Criteria) this;
        }

        public Criteria andNetmaskNotBetween(String value1, String value2) {
            addCriterion("NETMASK not between", value1, value2, "netmask");
            return (Criteria) this;
        }

        public Criteria andGatewayIsNull() {
            addCriterion("GATEWAY is null");
            return (Criteria) this;
        }

        public Criteria andGatewayIsNotNull() {
            addCriterion("GATEWAY is not null");
            return (Criteria) this;
        }

        public Criteria andGatewayEqualTo(String value) {
            addCriterion("GATEWAY =", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayNotEqualTo(String value) {
            addCriterion("GATEWAY <>", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayGreaterThan(String value) {
            addCriterion("GATEWAY >", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayGreaterThanOrEqualTo(String value) {
            addCriterion("GATEWAY >=", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayLessThan(String value) {
            addCriterion("GATEWAY <", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayLessThanOrEqualTo(String value) {
            addCriterion("GATEWAY <=", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayLike(String value) {
            addCriterion("GATEWAY like", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayNotLike(String value) {
            addCriterion("GATEWAY not like", value, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayIn(List<String> values) {
            addCriterion("GATEWAY in", values, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayNotIn(List<String> values) {
            addCriterion("GATEWAY not in", values, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayBetween(String value1, String value2) {
            addCriterion("GATEWAY between", value1, value2, "gateway");
            return (Criteria) this;
        }

        public Criteria andGatewayNotBetween(String value1, String value2) {
            addCriterion("GATEWAY not between", value1, value2, "gateway");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("USERNAME is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("USERNAME is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("USERNAME =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("USERNAME <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("USERNAME >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("USERNAME >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("USERNAME <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("USERNAME <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("USERNAME like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("USERNAME not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("USERNAME in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("USERNAME not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("USERNAME between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("USERNAME not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("PASSWORD =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("PASSWORD <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("PASSWORD >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("PASSWORD >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("PASSWORD <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("PASSWORD <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("PASSWORD like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("PASSWORD not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("PASSWORD in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("PASSWORD not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("PASSWORD between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("PASSWORD not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDevnameIsNull() {
            addCriterion("DEVNAME is null");
            return (Criteria) this;
        }

        public Criteria andDevnameIsNotNull() {
            addCriterion("DEVNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDevnameEqualTo(String value) {
            addCriterion("DEVNAME =", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameNotEqualTo(String value) {
            addCriterion("DEVNAME <>", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameGreaterThan(String value) {
            addCriterion("DEVNAME >", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameGreaterThanOrEqualTo(String value) {
            addCriterion("DEVNAME >=", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameLessThan(String value) {
            addCriterion("DEVNAME <", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameLessThanOrEqualTo(String value) {
            addCriterion("DEVNAME <=", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameLike(String value) {
            addCriterion("DEVNAME like", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameNotLike(String value) {
            addCriterion("DEVNAME not like", value, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameIn(List<String> values) {
            addCriterion("DEVNAME in", values, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameNotIn(List<String> values) {
            addCriterion("DEVNAME not in", values, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameBetween(String value1, String value2) {
            addCriterion("DEVNAME between", value1, value2, "devname");
            return (Criteria) this;
        }

        public Criteria andDevnameNotBetween(String value1, String value2) {
            addCriterion("DEVNAME not between", value1, value2, "devname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameIsNull() {
            addCriterion("DEVFRIENDLYNAME is null");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameIsNotNull() {
            addCriterion("DEVFRIENDLYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameEqualTo(String value) {
            addCriterion("DEVFRIENDLYNAME =", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameNotEqualTo(String value) {
            addCriterion("DEVFRIENDLYNAME <>", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameGreaterThan(String value) {
            addCriterion("DEVFRIENDLYNAME >", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameGreaterThanOrEqualTo(String value) {
            addCriterion("DEVFRIENDLYNAME >=", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameLessThan(String value) {
            addCriterion("DEVFRIENDLYNAME <", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameLessThanOrEqualTo(String value) {
            addCriterion("DEVFRIENDLYNAME <=", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameLike(String value) {
            addCriterion("DEVFRIENDLYNAME like", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameNotLike(String value) {
            addCriterion("DEVFRIENDLYNAME not like", value, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameIn(List<String> values) {
            addCriterion("DEVFRIENDLYNAME in", values, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameNotIn(List<String> values) {
            addCriterion("DEVFRIENDLYNAME not in", values, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameBetween(String value1, String value2) {
            addCriterion("DEVFRIENDLYNAME between", value1, value2, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andDevfriendlynameNotBetween(String value1, String value2) {
            addCriterion("DEVFRIENDLYNAME not between", value1, value2, "devfriendlyname");
            return (Criteria) this;
        }

        public Criteria andManagementagencyIsNull() {
            addCriterion("MANAGEMENTAGENCY is null");
            return (Criteria) this;
        }

        public Criteria andManagementagencyIsNotNull() {
            addCriterion("MANAGEMENTAGENCY is not null");
            return (Criteria) this;
        }

        public Criteria andManagementagencyEqualTo(String value) {
            addCriterion("MANAGEMENTAGENCY =", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyNotEqualTo(String value) {
            addCriterion("MANAGEMENTAGENCY <>", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyGreaterThan(String value) {
            addCriterion("MANAGEMENTAGENCY >", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyGreaterThanOrEqualTo(String value) {
            addCriterion("MANAGEMENTAGENCY >=", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyLessThan(String value) {
            addCriterion("MANAGEMENTAGENCY <", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyLessThanOrEqualTo(String value) {
            addCriterion("MANAGEMENTAGENCY <=", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyLike(String value) {
            addCriterion("MANAGEMENTAGENCY like", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyNotLike(String value) {
            addCriterion("MANAGEMENTAGENCY not like", value, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyIn(List<String> values) {
            addCriterion("MANAGEMENTAGENCY in", values, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyNotIn(List<String> values) {
            addCriterion("MANAGEMENTAGENCY not in", values, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyBetween(String value1, String value2) {
            addCriterion("MANAGEMENTAGENCY between", value1, value2, "managementagency");
            return (Criteria) this;
        }

        public Criteria andManagementagencyNotBetween(String value1, String value2) {
            addCriterion("MANAGEMENTAGENCY not between", value1, value2, "managementagency");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeIsNull() {
            addCriterion("IPCLONGITUDE is null");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeIsNotNull() {
            addCriterion("IPCLONGITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeEqualTo(String value) {
            addCriterion("IPCLONGITUDE =", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeNotEqualTo(String value) {
            addCriterion("IPCLONGITUDE <>", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeGreaterThan(String value) {
            addCriterion("IPCLONGITUDE >", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("IPCLONGITUDE >=", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeLessThan(String value) {
            addCriterion("IPCLONGITUDE <", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeLessThanOrEqualTo(String value) {
            addCriterion("IPCLONGITUDE <=", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeLike(String value) {
            addCriterion("IPCLONGITUDE like", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeNotLike(String value) {
            addCriterion("IPCLONGITUDE not like", value, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeIn(List<String> values) {
            addCriterion("IPCLONGITUDE in", values, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeNotIn(List<String> values) {
            addCriterion("IPCLONGITUDE not in", values, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeBetween(String value1, String value2) {
            addCriterion("IPCLONGITUDE between", value1, value2, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclongitudeNotBetween(String value1, String value2) {
            addCriterion("IPCLONGITUDE not between", value1, value2, "ipclongitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeIsNull() {
            addCriterion("IPCLATITUDE is null");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeIsNotNull() {
            addCriterion("IPCLATITUDE is not null");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeEqualTo(String value) {
            addCriterion("IPCLATITUDE =", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeNotEqualTo(String value) {
            addCriterion("IPCLATITUDE <>", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeGreaterThan(String value) {
            addCriterion("IPCLATITUDE >", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("IPCLATITUDE >=", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeLessThan(String value) {
            addCriterion("IPCLATITUDE <", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeLessThanOrEqualTo(String value) {
            addCriterion("IPCLATITUDE <=", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeLike(String value) {
            addCriterion("IPCLATITUDE like", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeNotLike(String value) {
            addCriterion("IPCLATITUDE not like", value, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeIn(List<String> values) {
            addCriterion("IPCLATITUDE in", values, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeNotIn(List<String> values) {
            addCriterion("IPCLATITUDE not in", values, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeBetween(String value1, String value2) {
            addCriterion("IPCLATITUDE between", value1, value2, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andIpclatitudeNotBetween(String value1, String value2) {
            addCriterion("IPCLATITUDE not between", value1, value2, "ipclatitude");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("VERSION is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("VERSION is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(String value) {
            addCriterion("VERSION =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(String value) {
            addCriterion("VERSION <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(String value) {
            addCriterion("VERSION >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(String value) {
            addCriterion("VERSION >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(String value) {
            addCriterion("VERSION <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(String value) {
            addCriterion("VERSION <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLike(String value) {
            addCriterion("VERSION like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotLike(String value) {
            addCriterion("VERSION not like", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<String> values) {
            addCriterion("VERSION in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<String> values) {
            addCriterion("VERSION not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(String value1, String value2) {
            addCriterion("VERSION between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(String value1, String value2) {
            addCriterion("VERSION not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andBranchIsNull() {
            addCriterion("BRANCH is null");
            return (Criteria) this;
        }

        public Criteria andBranchIsNotNull() {
            addCriterion("BRANCH is not null");
            return (Criteria) this;
        }

        public Criteria andBranchEqualTo(String value) {
            addCriterion("BRANCH =", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotEqualTo(String value) {
            addCriterion("BRANCH <>", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThan(String value) {
            addCriterion("BRANCH >", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchGreaterThanOrEqualTo(String value) {
            addCriterion("BRANCH >=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThan(String value) {
            addCriterion("BRANCH <", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLessThanOrEqualTo(String value) {
            addCriterion("BRANCH <=", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchLike(String value) {
            addCriterion("BRANCH like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotLike(String value) {
            addCriterion("BRANCH not like", value, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchIn(List<String> values) {
            addCriterion("BRANCH in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotIn(List<String> values) {
            addCriterion("BRANCH not in", values, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchBetween(String value1, String value2) {
            addCriterion("BRANCH between", value1, value2, "branch");
            return (Criteria) this;
        }

        public Criteria andBranchNotBetween(String value1, String value2) {
            addCriterion("BRANCH not between", value1, value2, "branch");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_IPC
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 08 22:33:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_IPC
     *
     * @mbggenerated Wed Apr 08 22:33:51 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}