package com.entity.videomonitor;

import java.util.ArrayList;
import java.util.List;

public class TVmManufacturerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public TVmManufacturerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andVendoridIsNull() {
            addCriterion("VENDORID is null");
            return (Criteria) this;
        }

        public Criteria andVendoridIsNotNull() {
            addCriterion("VENDORID is not null");
            return (Criteria) this;
        }

        public Criteria andVendoridEqualTo(String value) {
            addCriterion("VENDORID =", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotEqualTo(String value) {
            addCriterion("VENDORID <>", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThan(String value) {
            addCriterion("VENDORID >", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridGreaterThanOrEqualTo(String value) {
            addCriterion("VENDORID >=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThan(String value) {
            addCriterion("VENDORID <", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLessThanOrEqualTo(String value) {
            addCriterion("VENDORID <=", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridLike(String value) {
            addCriterion("VENDORID like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotLike(String value) {
            addCriterion("VENDORID not like", value, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridIn(List<String> values) {
            addCriterion("VENDORID in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotIn(List<String> values) {
            addCriterion("VENDORID not in", values, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridBetween(String value1, String value2) {
            addCriterion("VENDORID between", value1, value2, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendoridNotBetween(String value1, String value2) {
            addCriterion("VENDORID not between", value1, value2, "vendorid");
            return (Criteria) this;
        }

        public Criteria andVendornameIsNull() {
            addCriterion("VENDORNAME is null");
            return (Criteria) this;
        }

        public Criteria andVendornameIsNotNull() {
            addCriterion("VENDORNAME is not null");
            return (Criteria) this;
        }

        public Criteria andVendornameEqualTo(String value) {
            addCriterion("VENDORNAME =", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameNotEqualTo(String value) {
            addCriterion("VENDORNAME <>", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameGreaterThan(String value) {
            addCriterion("VENDORNAME >", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameGreaterThanOrEqualTo(String value) {
            addCriterion("VENDORNAME >=", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameLessThan(String value) {
            addCriterion("VENDORNAME <", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameLessThanOrEqualTo(String value) {
            addCriterion("VENDORNAME <=", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameLike(String value) {
            addCriterion("VENDORNAME like", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameNotLike(String value) {
            addCriterion("VENDORNAME not like", value, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameIn(List<String> values) {
            addCriterion("VENDORNAME in", values, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameNotIn(List<String> values) {
            addCriterion("VENDORNAME not in", values, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameBetween(String value1, String value2) {
            addCriterion("VENDORNAME between", value1, value2, "vendorname");
            return (Criteria) this;
        }

        public Criteria andVendornameNotBetween(String value1, String value2) {
            addCriterion("VENDORNAME not between", value1, value2, "vendorname");
            return (Criteria) this;
        }

        public Criteria andDesciptionIsNull() {
            addCriterion("DESCIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDesciptionIsNotNull() {
            addCriterion("DESCIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDesciptionEqualTo(String value) {
            addCriterion("DESCIPTION =", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionNotEqualTo(String value) {
            addCriterion("DESCIPTION <>", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionGreaterThan(String value) {
            addCriterion("DESCIPTION >", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCIPTION >=", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionLessThan(String value) {
            addCriterion("DESCIPTION <", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionLessThanOrEqualTo(String value) {
            addCriterion("DESCIPTION <=", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionLike(String value) {
            addCriterion("DESCIPTION like", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionNotLike(String value) {
            addCriterion("DESCIPTION not like", value, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionIn(List<String> values) {
            addCriterion("DESCIPTION in", values, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionNotIn(List<String> values) {
            addCriterion("DESCIPTION not in", values, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionBetween(String value1, String value2) {
            addCriterion("DESCIPTION between", value1, value2, "desciption");
            return (Criteria) this;
        }

        public Criteria andDesciptionNotBetween(String value1, String value2) {
            addCriterion("DESCIPTION not between", value1, value2, "desciption");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 04 10:55:07 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table T_VM_MANUFACTURER
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}