package com.entity.videomonitor;

public class TVmManufacturer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_MANUFACTURER.VENDORID
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    private String vendorid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_MANUFACTURER.VENDORNAME
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    private String vendorname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_MANUFACTURER.DESCIPTION
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    private String desciption;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_MANUFACTURER.VENDORID
     *
     * @return the value of T_VM_MANUFACTURER.VENDORID
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public String getVendorid() {
        return vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_MANUFACTURER.VENDORID
     *
     * @param vendorid the value for T_VM_MANUFACTURER.VENDORID
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void setVendorid(String vendorid) {
        this.vendorid = vendorid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_MANUFACTURER.VENDORNAME
     *
     * @return the value of T_VM_MANUFACTURER.VENDORNAME
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public String getVendorname() {
        return vendorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_MANUFACTURER.VENDORNAME
     *
     * @param vendorname the value for T_VM_MANUFACTURER.VENDORNAME
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void setVendorname(String vendorname) {
        this.vendorname = vendorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_MANUFACTURER.DESCIPTION
     *
     * @return the value of T_VM_MANUFACTURER.DESCIPTION
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public String getDesciption() {
        return desciption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_MANUFACTURER.DESCIPTION
     *
     * @param desciption the value for T_VM_MANUFACTURER.DESCIPTION
     *
     * @mbggenerated Sat Apr 04 10:55:07 CST 2015
     */
    public void setDesciption(String desciption) {
        this.desciption = desciption;
    }
}