package com.entity.videomonitor;

import java.math.BigDecimal;
import java.util.Map;

import net.sf.oval.constraint.Length;
import net.sf.oval.constraint.MatchPattern;
import net.sf.oval.constraint.MaxSize;
import net.sf.oval.constraint.MemberOf;
import net.sf.oval.constraint.NotEmpty;
import net.sf.oval.constraint.NotNull;

public class TVmNvr {

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.NVRID
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
	@NotNull(message = "NVR ID不能为空")
	@NotEmpty(message = "NVR ID不能为空")
	@Length(max = 7,message="NVR ID最长为7位")
    private String nvrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.VENDORID
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    //private String vendorid;
    private TVmManufacturer vendor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.IP
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    @NotNull(message = "IP不能为空")
	@NotEmpty(message = "IP不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "IP格式错误")
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.PORT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    @NotNull(message = "Port不能为空")
	@NotEmpty(message = "Port不能为空")
	@MatchPattern(pattern = "^\\d+$",message ="Port只能为整数")
    private BigDecimal port;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.NETMASK
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    @NotNull(message = "netmask不能为空")
	@NotEmpty(message = "netmask不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "netmask格式错误")
    private String netmask;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.GATEWAY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    @NotNull(message = "gateway不能为空")
	@NotEmpty(message = "gateway不能为空")
	@MatchPattern(pattern = "^(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)(\\.(25[0-5]|2[0-4]\\d|[0-1]?\\d?\\d)){3}$", message = "gateway格式错误")
    private String gateway;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.USERNAME2
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
	@NotNull(message = "用户名不能为空")
	@NotEmpty(message = "用户名不能为空")
    private String username2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.PASSWORD
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
	@NotNull(message = "密码不能为空")
	@NotEmpty(message = "密码不能为空")
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.DEVNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
	@NotNull(message = "devname不能为空")
	@NotEmpty(message = "devname不能为空")
	@Length(max = 32, message = "devname最长为32位")
    private String devname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.DEVFRIENDLYNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    private String devfriendlyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.DISKNUM
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    private BigDecimal disknum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.MANAGEMENTAGENCY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    private String managementagency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.VERSION
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    private String version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_VM_NVR.NVRFAULT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    private String branch;
    
    private String devtype;
    @MemberOf(value={"0","1"},message="NVRFAULT只能是0或者1")
    private int nvrFault;
    
    private Map<String,String> state;

    public Map<String, String> getState() {
		return state;
	}

	public void setState(Map<String, String> state) {
		this.state = state;
	}

	public String getDevtype() {
		return devtype;
	}

	public void setDevtype(String devtype) {
		this.devtype = devtype;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.NVRID
     *
     * @return the value of T_VM_NVR.NVRID
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getNvrid() {
        return nvrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.NVRID
     *
     * @param nvrid the value for T_VM_NVR.NVRID
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setNvrid(String nvrid) {
        this.nvrid = nvrid;
    }


    
    public TVmManufacturer getVendor() {
		return vendor;
	}

	public void setVendor(TVmManufacturer vendor) {
		this.vendor = vendor;
	}

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.IP
     *
     * @return the value of T_VM_NVR.IP
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.IP
     *
     * @param ip the value for T_VM_NVR.IP
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.PORT
     *
     * @return the value of T_VM_NVR.PORT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public BigDecimal getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.PORT
     *
     * @param port the value for T_VM_NVR.PORT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setPort(BigDecimal port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.NETMASK
     *
     * @return the value of T_VM_NVR.NETMASK
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getNetmask() {
        return netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.NETMASK
     *
     * @param netmask the value for T_VM_NVR.NETMASK
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setNetmask(String netmask) {
        this.netmask = netmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.GATEWAY
     *
     * @return the value of T_VM_NVR.GATEWAY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getGateway() {
        return gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.GATEWAY
     *
     * @param gateway the value for T_VM_NVR.GATEWAY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setGateway(String gateway) {
        this.gateway = gateway;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.USERNAME2
     *
     * @return the value of T_VM_NVR.USERNAME2
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getUsername2() {
        return username2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.USERNAME2
     *
     * @param username2 the value for T_VM_NVR.USERNAME2
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setUsername2(String username2) {
        this.username2 = username2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.PASSWORD
     *
     * @return the value of T_VM_NVR.PASSWORD
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.PASSWORD
     *
     * @param password the value for T_VM_NVR.PASSWORD
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.DEVNAME
     *
     * @return the value of T_VM_NVR.DEVNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getDevname() {
        return devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.DEVNAME
     *
     * @param devname the value for T_VM_NVR.DEVNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setDevname(String devname) {
        this.devname = devname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.DEVFRIENDLYNAME
     *
     * @return the value of T_VM_NVR.DEVFRIENDLYNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getDevfriendlyname() {
        return devfriendlyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.DEVFRIENDLYNAME
     *
     * @param devfriendlyname the value for T_VM_NVR.DEVFRIENDLYNAME
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setDevfriendlyname(String devfriendlyname) {
        this.devfriendlyname = devfriendlyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.DISKNUM
     *
     * @return the value of T_VM_NVR.DISKNUM
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public BigDecimal getDisknum() {
        return disknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.DISKNUM
     *
     * @param disknum the value for T_VM_NVR.DISKNUM
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setDisknum(BigDecimal disknum) {
        this.disknum = disknum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.MANAGEMENTAGENCY
     *
     * @return the value of T_VM_NVR.MANAGEMENTAGENCY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getManagementagency() {
        return managementagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.MANAGEMENTAGENCY
     *
     * @param managementagency the value for T_VM_NVR.MANAGEMENTAGENCY
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setManagementagency(String managementagency) {
        this.managementagency = managementagency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.VERSION
     *
     * @return the value of T_VM_NVR.VERSION
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.VERSION
     *
     * @param version the value for T_VM_NVR.VERSION
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_VM_NVR.NVRFAULT
     *
     * @return the value of T_VM_NVR.NVRFAULT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public String getBranch() {
        return branch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_VM_NVR.NVRFAULT
     *
     * @param nvrfault the value for T_VM_NVR.NVRFAULT
     *
     * @mbggenerated Sat Apr 04 10:52:12 CST 2015
     */
    public void setBranch(String branch) {
        this.branch = branch;
    }

	public int getNvrFault() {
		return nvrFault;
	}

	public void setNvrFault(int nvrFault) {
		this.nvrFault = nvrFault;
	}
    
}